### ISSUE TITLE
adminModel InvalidArgumentException on one env but not another

### ISSUE THREAD

**Issue by uzegonemad** [sleeping-owl/admin#214]
On my local env, the admin loads just fine, but on my remote dev env, I get the following exception when I attempt to load admin screens.

As far as I know there is no major difference between the environments to cause this. Any advice?

```
[2015-08-20 18:38:23] production.ERROR: exception 'InvalidArgumentException' with message 'Routing requirement for "adminModel" cannot be empty.' in /var/www/bootstrap/cache/compiled.php:8383
Stack trace:
#0 /var/www/bootstrap/cache/compiled.php(8329): Symfony\Component\Routing\Route->sanitizeRequirement('adminModel', '')
#1 /var/www/bootstrap/cache/compiled.php(8324): Symfony\Component\Routing\Route->addRequirements(Array)
#2 /var/www/bootstrap/cache/compiled.php(8159): Symfony\Component\Routing\Route->setRequirements(Array)
#3 /var/www/bootstrap/cache/compiled.php(7519): Symfony\Component\Routing\Route->__construct('dashboard/login', Array, Array, Array, '')
#4 /var/www/bootstrap/cache/compiled.php(7504): Illuminate\Routing\Route->compileRoute()
#5 /var/www/bootstrap/cache/compiled.php(7910): Illuminate\Routing\Route->matches(Object(Illuminate\Http\Request), true)
#6 [internal function]: Illuminate\Routing\RouteCollection->Illuminate\Routing\{closure}('dashboard/login', Object(Illuminate\Routing\Route))
#7 /var/www/bootstrap/cache/compiled.php(5841): call_user_func(Object(Closure), 'dashboard/login', Object(Illuminate\Routing\Route))
#8 /var/www/bootstrap/cache/compiled.php(7911): Illuminate\Support\Arr::first(Array, Object(Closure))
#9 /var/www/bootstrap/cache/compiled.php(7873): Illuminate\Routing\RouteCollection->check(Array, Object(Illuminate\Http\Request))
#10 /var/www/bootstrap/cache/compiled.php(7141): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#11 /var/www/bootstrap/cache/compiled.php(7106): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#12 /var/www/bootstrap/cache/compiled.php(7098): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/bootstrap/cache/compiled.php(2088): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/bootstrap/cache/compiled.php(9196): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/bootstrap/cache/compiled.php(2708): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#19 /var/www/bootstrap/cache/compiled.php(12456): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#22 /var/www/bootstrap/cache/compiled.php(11104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#25 /var/www/bootstrap/cache/compiled.php(12193): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#28 /var/www/bootstrap/cache/compiled.php(12132): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#31 /var/www/bootstrap/cache/compiled.php(2758): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/bootstrap/cache/compiled.php(9188): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/bootstrap/cache/compiled.php(9178): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/bootstrap/cache/compiled.php(2035): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /var/www/bootstrap/cache/compiled.php(2018): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#38 /var/www/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#39 {main}
```

**Comment by noxify** [comment]
Maybe you have to run `composer dump autoload` ?
Did you changed something after deployment to your remote dev?

**Comment by uzegonemad** [comment]
I dumped composer, cleared all laravel caches/compiled files, deleted the vendor folder and reinstalled, the whole nine years - nothing worked. Very bizarre!

**Comment by noxify** [comment]
* Which Version are you using?
* Can you paste your composer.json? So I can test it on my DEV Environment

Thanks

**Comment by uzegonemad** [comment]
I'm on the latest v3 - probably should have mentioned that before, sorry!

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laravelcollective/html": "dev-master",

        "fzaninotto/faker": "^1.5",

        "sleeping-owl/admin": "dev-development",
        "sleeping-owl/admin-lte-template": "dev-master"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",

        "barryvdh/laravel-ide-helper": "~2.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled",
            "php artisan ide-helper:generate",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

Thank you!

**Comment by uzegonemad** [comment]
I had upgraded from v2 to v3 and didn't notice that the bootstrap directory had changed in https://github.com/sleeping-owl/admin/commit/24f0ebc02e00ed7bf9e3bfab3628ac45fab331be.

My local environment is case-insensitive, but it would appear that the production env is case-sensitive.
